name: Daily update with new blog post content
on: 
  schedule:
      # Runs every day in December at 0:00 UTC
    - cron: '0 0 * 12 *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # login to azure account with service principal 
      - name: Login to Azure
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}    
          enable-AzPSSession: true 
      - uses: actions/checkout@v2
      - run: |
          ./powershell/updatecalendar.ps1
        shell: pwsh        
      - name: Commit file changes
        run: |
            git config --global user.name 'alankinane'
            git config --global user.email 'alankinane@gmail.com'
            git add calendar.html
            git diff --quiet --cached || git commit -m "Update Calendar" 
      - name: Push changes
        uses: ad-m/github-push-action@master        
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}